title = "oh_long_johnson"
baseURL = "https://phrmendes.github.io/"
theme = "hugo-bearblog"
enableEmoji = true
enableRobotsTXT = true

[params]
author = "Pedro Mendes"
description = "My resume"
favicon = "icon.png"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "CV"
url = "/cv"
